const questionPhrases = [
"what do you think of ",
"have you had any significant life experiences involving ",
"what is your first memory of ",
"what would you do if you were reborn as ",
"how often do you think about ",
"do your friends like ",
"what if I told you I have glimpsed the inner quintessence of ",
"what is the weightiest you have ever seen of ",
"what would you say if you were to anthropomorphose ",
"can you think of any smells associated with ",
"what kind of people generally are into ",
"can you tell where online i might find more information on ",
"In terms of value, how would you rate ",
"where do you think is the best place to buy gifts associated with ",
"what would the world be like if there was no ",
"how would we get by in the world if it weren't for ",
"you know what they say about ",
"depending on where you live, you might not wanna publicly talk about ",
"what do you think the future holds for ",
"what would you do if you youself could possess what you value in ",
"what would you do if you were stuck with ",
"do you think is good eating, what this food you call ",
"when was the last time you interacted with ",
"you ever had any other dreams about this ",
"try for youself to think for a minute what it would be like to be ",
"how intelligent do you think is ",
"do not try and bend the spoon, that's impossible. Instead, only try to realize the truth...there is no ",
"once for nearly a fortnight I became the most tiny of ",
"do or do not, there is no ",
"i once cured hiccups with ",
"the other day I saw old mister whatshisname heading into the woods carrying ",
"if you could only have one kind for the rest of your life, what kind would you pick of ",
"when was the last time you saw at a yard sale ",
"it was foretold in a prophecy, you and this ",
"who stands to gain if there were no more ",
"has anyone recenently warned you about ",
"aren't we all just looking for ",
"the best part about being 9000 years old is that I don't have to worry about ",
"one time i saw a documentary about ",
"there's a really cool website about door, it's totallysweet.com/",
"this morning I saw a piece on the Today show about ",
"what was it Abraham Lincoln said about ",
"i wouldn't have spent that year in college if it weren't for ",
"do you think early humans had much of a concept of ",
"can you imagine if your name was ",
"i heard your friend's cousin got legally married to a ",
"where in canada can you get the best ",



]  

export default questionPhrases;